export const UPDATE_CURRENT_FIGHT = "UPDATE_CURRENT_FIGHT";
export const UPDATE_FIGHT_CODE = "UPDATE_FIGHT_CODE";
export const UPDATE_SLIDE_COMPARE_FLAG = "UPDATE_SLIDE_COMPARE_FLAG";
export const RESET_FIGHT_CODE = "RESET_FIGHT_CODE";
export const SUBMIT_FIGHT = "SUBMIT_FIGHT";
export const UPDATE_USER_LOGIN = "UPDATE_USER_LOGIN";
